@extends('tenant-marketplace.layout')
@section('title', 'Advertise your rental property | Starmax Homes')
@section('meta_description', 'Advertise a vacant rental home on Starmax Homes and manage enquiries, tenants, rent and maintenance in one place.')
@section('content')
<section class="inner-hero advertise-hero"><div class="market-shell advertise-hero-grid"><div><span class="hero-kicker">For owners & property managers</span><h1>Turn a vacancy into a <em>new tenancy.</em></h1><p>Show renters what makes your home right for them, receive private viewing requests, then manage the tenancy with Starmax.</p><div class="advertise-actions"><a class="primary-action" href="#get-started">Get started →</a><a href="{{ route('admin.login') }}" target="_blank" rel="noopener noreferrer" aria-label="Property manager sign in (opens in a new tab)">Already use Starmax? Sign in</a></div></div><div class="listing-preview"><div class="preview-photo"><span>Your best property photo</span></div><div><small>LIVE AVAILABILITY</small><h3>Your property name</h3><p>Your location</p><strong>KSh — <span>/ month</span></strong></div></div></div></section>
<section class="market-shell editorial-section"><div class="home-section-heading"><div><span class="section-kicker">A stronger advert</span><h2>Give renters the details they use to decide.</h2></div></div><div class="benefit-grid"><article><h3>Bright, honest photos</h3><p>Show the exterior and every important room in natural light. Current photos help renters understand the layout.</p></article><article><h3>Complete home details</h3><p>Add the exact location, bedrooms, floor, monthly rent and a concise description of what is special.</p></article><article><h3>Accurate availability</h3><p>Your public advert reflects available units, so occupied homes do not keep attracting enquiries.</p></article><article><h3>One organised workflow</h3><p>Move from enquiry to tenant management, rent collection, invoices and maintenance in the same platform.</p></article></div></section>
<section id="get-started" class="lead-section"><div class="market-shell lead-grid"><div><span class="section-kicker">Start advertising</span><h2>Tell us about your property.</h2><p>Send a few basics. The Starmax team can help you set up the property, its available units and the public listing.</p><div class="lead-checklist"><span>✓ Property and unit setup</span><span>✓ Listing quality review</span><span>✓ Enquiry and tenant tools</span></div></div><form action="{{ route('marketplace.contact.submit') }}" method="POST" class="advertise-form">@csrf
@if(session('success'))<div class="success-message" role="status">{{ session('success') }}</div>@endif
@if($errors->any())<div class="field-error" role="alert">Please check your name, email and property details, then try again.</div>@endif
<input type="hidden" name="service" value="tenant"><label>Your name<input name="name" required value="{{ old('name') }}" autocomplete="name"></label><label>Work email<input type="email" name="email" required value="{{ old('email') }}" autocomplete="email"></label><label>Property details<textarea name="message" required rows="5" placeholder="Property location, number of available homes and the best phone number to reach you">{{ old('message') }}</textarea></label><button type="submit">Request listing support →</button><small>We’ll use these details only to respond to your property-listing request.</small></form></div></section>
@endsection
