@extends('tenant-marketplace.layout')
@section('title', 'Rent safely: viewing and move-in checklist | Starmax Homes')
@section('meta_description', 'A practical rental checklist: verify the home and manager, understand move-in costs, inspect the unit, protect your information and report suspicious listings.')
@section('content')
<section class="inner-hero safety-hero"><div class="market-shell inner-hero-grid"><div><span class="hero-kicker">The renting guide</span><h1>Find your home.<br>Take the next step with confidence.</h1><p>A practical checklist for the search, the viewing and the moment you are ready to move in.</p><div class="hero-links"><a class="primary-action" href="#viewing-checklist">Your viewing checklist</a><a class="text-link" href="#red-flags">Know the warning signs</a></div></div><aside class="hero-guide-card"><span class="section-kicker">Three things to remember</span><ol><li>See the exact unit.</li><li>Check who manages it.</li><li>Agree all costs in writing.</li></ol><p>A listing is an introduction. Your own checks still matter.</p></aside></div></section>
<nav class="market-shell guide-jump-links" aria-label="Safety guide sections"><a href="#before-viewing">Before the viewing</a><a href="#viewing-checklist">At the viewing</a><a href="#before-paying">Before you pay</a><a href="#red-flags">Warning signs</a><a href="#get-help">Get help</a></nav>
<section class="market-shell editorial-section safety-content">
    <article id="before-viewing" class="guide-chapter"><div class="chapter-heading"><span>01</span><div><p class="section-kicker">Before the viewing</p><h2>Make sure the basics add up.</h2></div></div><div class="safety-grid"><div><h3>Know what you are viewing</h3><p>Save the listing link and confirm the property, exact unit number, location, asking rent and who you are meeting. Ask for current unit photos if only building photos are shown.</p></div><div><h3>Plan a realistic budget</h3><p>Ask for rent, deposit, service charge, water, garbage and any one-time fees separately. A known subtotal is not the final amount when some fees are missing. Allow for electricity and moving expenses too.</p></div><div><h3>Arrange a sensible visit</h3><p>Choose a time when you can properly inspect the home and area. Let someone you trust know where you are going, or bring them along. If you cannot attend, ask a trusted person to visit for you.</p></div></div></article>
    <article id="viewing-checklist" class="guide-chapter"><div class="chapter-heading"><span>02</span><div><p class="section-kicker">At the viewing</p><h2>Check the home you will actually live in.</h2></div></div><p>Tick each item after checking it during your viewing. Your progress is a personal reminder and resets when you reload this page.</p><div class="checklist-progress" data-checklist-progress hidden><p role="status" aria-live="polite" data-checklist-count>0 of 8 checks completed</p><progress data-checklist-meter max="8" value="0" aria-label="Viewing checklist completion"></progress><button type="button" class="text-button" data-checklist-reset disabled>Reset checklist</button></div><div class="viewing-checklist">
    @foreach(['The unit number and rooms match the advert.', 'Doors, windows and locks work; access and exits are clear.', 'Taps, toilets and drainage work; ask about water interruptions.', 'Check for damp, leaks, damaged fittings and obvious maintenance issues.', 'Confirm electricity metering, internet options and any recurring charges.', 'Check phone reception, noise, natural light and your usual commute.', 'Confirm parking, visitor rules, pets and accessibility where relevant.', 'Ask which repairs will be completed before move-in and get them recorded.'] as $item)<label><input type="checkbox"> <span>{{ $item }}</span></label>@endforeach
    </div><p class="fact-note">Take condition photos with permission and keep a record of agreed repairs. Do not touch exposed wiring or unsafe fittings; ask the manager to address them.</p></article>
    <article id="before-paying" class="guide-chapter"><div class="chapter-heading"><span>03</span><div><p class="section-kicker">Before you pay</p><h2>Put the agreement and payment details together.</h2></div></div><div class="safety-grid"><div><h3>Confirm the representative</h3><p>Ask who owns or manages the property and how the representative is authorised to act. Check through an established management contact. A familiar logo or a listing on a website is not proof of authority.</p></div><div><h3>Read the written terms</h3><p>Check the correct unit, start date, rent, deposit, fee schedule, repair responsibilities, notice terms and deposit-return conditions. Ask about anything unclear before you commit and keep your copy.</p></div><div><h3>Verify where money goes</h3><p>Confirm the recipient name and payment reference against written management instructions. Independently check unexpected changes to payment details. Never share your PIN, password or one-time security codes. Keep receipts and transaction references.</p></div></div></article>
    <article id="red-flags" class="warning-panel"><span class="section-kicker">Pause and check</span><h2>Warning signs worth taking seriously</h2><ul><li>Pressure to pay immediately before viewing or reading the agreement.</li><li>A representative who will not show the exact unit or explain their authority.</li><li>Photos, location or prices that change when you ask questions.</li><li>Requests to pay an unexplained recipient, or sudden changes to payment details.</li><li>Requests for security codes, account passwords or excessive personal documents.</li></ul><p>One concern is a reason to ask more questions. If the answers do not add up, stop the transaction.</p></article>
    <article class="guide-chapter"><div class="chapter-heading"><span>04</span><div><p class="section-kicker">On move-in day</p><h2>Keep a clear handover record.</h2></div></div><p>Confirm the keys and access devices you receive. Record meter readings, existing damage and any unfinished repairs with the manager. Keep the agreement, receipts, inventory and repair commitments together so you can refer to them later.</p></article>
    <section id="get-help" class="area-callout"><div><span class="section-kicker">If something goes wrong</span><h2>Keep the evidence. Ask for help promptly.</h2><p>Use Report this listing on the property page to flag inaccurate details or a suspicious request. Keep the listing URL, messages and payment references. If you suspect fraud after paying, contact your payment provider promptly and report the matter to the police. For immediate danger, contact local emergency services.</p><p>Starmax listing reports go to our review team; they do not reverse payments or replace emergency assistance.</p></div><a class="secondary-action" href="{{ route('marketplace.contact') }}">Contact Starmax support</a></section>
    <section class="safety-faq"><h2>Common questions</h2><details><summary>Does ?managed on Starmax? mean a home is independently verified?</summary><p>It means the property manager uses Starmax. It is not a guarantee of the property, ownership, condition or a representative's identity. Complete your own checks.</p></details><details><summary>Does a viewing request reserve the home?</summary><p>No. A viewing enquiry asks the manager to contact you. Confirm availability and any reservation terms directly before committing.</p></details><details><summary>What does ?availability checked? mean?</summary><p>The manager explicitly confirmed availability on the displayed date. Circumstances can change afterwards, so reconfirm before travelling.</p></details><details><summary>Why is the move-in figure sometimes a subtotal?</summary><p>A subtotal adds only the recorded charges. A missing deposit or fee is not treated as zero. Ask the manager for the complete written amount before paying.</p></details></section>
</section>
@endsection
